name: Testing Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission to gradlew
        run: chmod a+x ./gradlew

      - name: Run Android Linter
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

#       Instructions to run UI tests on Firebase Test Lab

#      - name: Assemble Debug APK
#        run: ./gradlew assembleDebug

#      - name: Assemble Debug Test APK
#        run: ./gradlew assembleDebugAndroidTest

#      - name: Run tests on Firebase Test Lab
#        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
#        with:
#          arg-spec: '.github/test-lab-config-staging.yml:android-pixel-4'
#        env:
#          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}